/**
 * AdminPromoCodes
 * /admin/promo
 *
 * CHANGES:
 * - Removed `code` input (auto-generated by backend)
 * - Removed `expiresAt` input (computed: startsAt + durationDays)
 * - Added `startsAt` date picker
 * - Added live preview: "Active from X → expires Y"
 * - Status badge now uses the `status` virtual from the model:
 *   scheduled | active | expired | exhausted | disabled
 */

import { useState, useEffect, useCallback } from 'react';
import api from '../../services/api.js';
import toast from 'react-hot-toast';
import {
  Tag, Plus, ToggleLeft, ToggleRight,
  Copy, RefreshCw, Clock, CheckCircle,
  XCircle, Hourglass, ZapOff,
} from 'lucide-react';
import styles from './Admin.module.css';

// ── helpers ──────────────────────────────────────────────────────────────────

const fmt = (d) =>
  new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

const todayISO = () => new Date().toISOString().split('T')[0];

const addDays = (isoDate, days) => {
  const d = new Date(isoDate);
  d.setDate(d.getDate() + days);
  return fmt(d);
};

const STATUS_META = {
  active:    { label: 'Active',     color: '#16A34A', bg: '#F0FDF4', Icon: CheckCircle },
  scheduled: { label: 'Scheduled',  color: '#D97706', bg: '#FFFBEB', Icon: Clock       },
  expired:   { label: 'Expired',    color: '#DC2626', bg: '#FEF2F2', Icon: XCircle     },
  exhausted: { label: 'Exhausted',  color: '#6B7280', bg: '#F3F4F6', Icon: Hourglass   },
  disabled:  { label: 'Disabled',   color: '#6B7280', bg: '#F3F4F6', Icon: ZapOff      },
};

const EMPTY_FORM = {
  plan:         'pro',
  durationDays: 14,
  maxUses:      100,
  startsAt:     todayISO(),
  description:  '',
};

// ── component ─────────────────────────────────────────────────────────────────

export default function AdminPromoCodes() {
  const [promos,   setPromos]   = useState([]);
  const [loading,  setLoading]  = useState(true);
  const [form,     setForm]     = useState(EMPTY_FORM);
  const [saving,   setSaving]   = useState(false);
  const [showForm, setShowForm] = useState(false);

  const fetchPromos = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/promo/admin/list');
      setPromos(data.promos);
    } catch {
      toast.error('Failed to load promo codes.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchPromos(); }, [fetchPromos]);

  const handleCreate = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const { data } = await api.post('/promo/admin/create', form);
      toast.success(`Code "${data.promo.code}" created!`);
      setForm(EMPTY_FORM);
      setShowForm(false);
      fetchPromos();
    } catch (err) {
      toast.error(err?.response?.data?.error || 'Failed to create code.');
    } finally {
      setSaving(false);
    }
  };

  const handleToggle = async (id, currentActive) => {
    try {
      await api.patch(`/promo/admin/${id}/toggle`);
      setPromos((prev) =>
        prev.map((p) =>
          p._id === id
            ? { ...p, isActive: !currentActive, status: !currentActive ? 'active' : 'disabled' }
            : p
        )
      );
      toast.success(`Code ${currentActive ? 'deactivated' : 'activated'}.`);
    } catch {
      toast.error('Failed to toggle code.');
    }
  };

  const copyCode = (code) => {
    navigator.clipboard.writeText(code).then(() => toast.success('Copied!'));
  };

  // Live preview: "Active Mar 1 → Mar 15"
  const previewExpiry = form.startsAt
    ? addDays(form.startsAt, Number(form.durationDays) || 0)
    : null;

  return (
    <div className="fade-up">

      {/* ── Header ── */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <h2 style={{ fontFamily: "'DM Serif Display', serif", fontSize: '1.6rem', marginBottom: 4 }}>
            Promo Codes
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
            Codes are auto-generated. Set a start date and duration — expiry is calculated automatically.
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-secondary btn-sm" onClick={fetchPromos}>
            <RefreshCw size={14} /> Refresh
          </button>
          <button className="btn btn-primary btn-sm" onClick={() => setShowForm((v) => !v)}>
            <Plus size={14} /> {showForm ? 'Cancel' : 'New Code'}
          </button>
        </div>
      </div>

      {/* ── Create form ── */}
      {showForm && (
        <form
          onSubmit={handleCreate}
          style={{
            background: 'white', border: '1.5px solid var(--border)',
            borderRadius: 'var(--radius-lg)', padding: '28px',
            marginBottom: 28,
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
            gap: '16px',
          }}
        >
          {/* Plan */}
          <div className="form-group">
            <label className="form-label">Plan</label>
            <select
              className="form-input"
              value={form.plan}
              onChange={(e) => setForm({ ...form, plan: e.target.value })}
            >
              <option value="pro">Pro</option>
              <option value="premium">Premium</option>
            </select>
          </div>

          {/* Duration */}
          <div className="form-group">
            <label className="form-label">Duration (days)</label>
            <input
              type="number" className="form-input" min={1} max={365}
              value={form.durationDays}
              onChange={(e) => setForm({ ...form, durationDays: Number(e.target.value) })}
              required
            />
          </div>

          {/* Max uses */}
          <div className="form-group">
            <label className="form-label">Max Uses</label>
            <input
              type="number" className="form-input" min={1}
              value={form.maxUses}
              onChange={(e) => setForm({ ...form, maxUses: Number(e.target.value) })}
              required
            />
          </div>

          {/* Start date */}
          <div className="form-group">
            <label className="form-label">Starts At</label>
            <input
              type="date" className="form-input"
              value={form.startsAt}
              min={todayISO()}
              onChange={(e) => setForm({ ...form, startsAt: e.target.value })}
              required
            />
          </div>

          {/* Description — full width */}
          <div className="form-group" style={{ gridColumn: '1 / -1' }}>
            <label className="form-label">Description (optional)</label>
            <input
              className="form-input"
              placeholder="e.g. Product Hunt launch — April 2025"
              value={form.description}
              onChange={(e) => setForm({ ...form, description: e.target.value })}
              maxLength={200}
            />
          </div>

          {/* Live preview — full width */}
          {previewExpiry && (
            <div
              style={{
                gridColumn: '1 / -1',
                background: '#F0FDF4', border: '1px solid #BBF7D0',
                borderRadius: 'var(--radius)', padding: '10px 14px',
                fontSize: '0.85rem', color: '#15803D',
                display: 'flex', alignItems: 'center', gap: 8,
              }}
            >
              <CheckCircle size={14} />
              Code will be active from{' '}
              <strong>{fmt(form.startsAt)}</strong>
              {' '}and expire on{' '}
              <strong>{previewExpiry}</strong>
              {' '}· Up to <strong>{form.maxUses} uses</strong>
            </div>
          )}

          {/* Actions */}
          <div style={{ gridColumn: '1 / -1', display: 'flex', gap: 10 }}>
            <button type="submit" className="btn btn-primary" disabled={saving}>
              {saving
                ? <span className="spinner" style={{ width: 14, height: 14, borderColor: 'rgba(255,255,255,.3)', borderTopColor: '#fff' }} />
                : <Plus size={14} />}
              Generate Code
            </button>
            <button type="button" className="btn btn-secondary" onClick={() => setShowForm(false)}>
              Cancel
            </button>
          </div>
        </form>
      )}

      {/* ── List ── */}
      {loading ? (
        <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
          <div className="spinner" style={{ width: 28, height: 28 }} />
        </div>
      ) : promos.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '64px 24px', color: 'var(--text-secondary)' }}>
          <Tag size={40} style={{ marginBottom: 12, opacity: .3 }} />
          <p>No promo codes yet. Create one above.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {promos.map((p) => {
            const meta     = STATUS_META[p.status] ?? STATUS_META.disabled;
            const StatusIcon = meta.Icon;
            const usagePct = Math.min(100, Math.round((p.usedCount / p.maxUses) * 100));

            return (
              <div
                key={p._id}
                style={{
                  background: 'white',
                  border: `1.5px solid ${p.status === 'active' ? 'var(--border)' : '#FCA5A5'}`,
                  borderRadius: 'var(--radius)',
                  padding: '16px 20px',
                  display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap',
                  opacity: p.status === 'disabled' ? 0.65 : 1,
                }}
              >
                {/* Code + copy */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 160 }}>
                  <span style={{
                    fontFamily: 'monospace', fontWeight: 800, fontSize: '1rem',
                    letterSpacing: '0.1em',
                    color: p.status === 'active' ? 'var(--text)' : 'var(--muted)',
                  }}>
                    {p.code}
                  </span>
                  <button
                    onClick={() => copyCode(p.code)}
                    style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--muted)', padding: 2 }}
                    title="Copy code"
                  >
                    <Copy size={13} />
                  </button>
                </div>

                {/* Plan badge */}
                <span style={{
                  padding: '3px 10px', borderRadius: 20, fontSize: '0.75rem', fontWeight: 700,
                  background: p.plan === 'premium' ? '#FFF3EE' : '#EFF6FF',
                  color:      p.plan === 'premium' ? 'var(--brand)' : '#3B82F6',
                }}>
                  {p.plan.toUpperCase()}
                </span>

                {/* Duration */}
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                  {p.durationDays}d trial
                </span>

                {/* Date window */}
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                  {fmt(p.startsAt)} → {fmt(p.expiresAt)}
                </span>

                {/* Usage bar */}
                <div style={{ flex: 1, minWidth: 120 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: 4 }}>
                    <span>{p.usedCount} / {p.maxUses} uses</span>
                    <span>{usagePct}%</span>
                  </div>
                  <div style={{ height: 4, background: 'var(--sand)', borderRadius: 4 }}>
                    <div style={{
                      height: '100%', width: `${usagePct}%`, borderRadius: 4,
                      background: usagePct >= 100 ? '#DC2626' : usagePct > 80 ? '#F59E0B' : 'var(--brand)',
                      transition: 'width .3s',
                    }} />
                  </div>
                </div>

                {/* Status badge */}
                <span style={{
                  display: 'flex', alignItems: 'center', gap: 5,
                  padding: '4px 10px', borderRadius: 20,
                  fontSize: '0.75rem', fontWeight: 700,
                  background: meta.bg, color: meta.color,
                  whiteSpace: 'nowrap',
                }}>
                  <StatusIcon size={12} />
                  {meta.label}
                </span>

                {/* Toggle */}
                <button
                  onClick={() => handleToggle(p._id, p.isActive)}
                  style={{
                    background: 'none', border: 'none', cursor: 'pointer',
                    color: p.isActive ? 'var(--success)' : 'var(--muted)', padding: 4,
                    marginLeft: 'auto',
                  }}
                  title={p.isActive ? 'Deactivate' : 'Activate'}
                >
                  {p.isActive ? <ToggleRight size={22} /> : <ToggleLeft size={22} />}
                </button>

                {/* Description */}
                {p.description && (
                  <div style={{
                    width: '100%', fontSize: '0.8rem', color: 'var(--muted)',
                    paddingTop: 8, borderTop: '1px solid var(--border)',
                  }}>
                    {p.description}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}